@startuml
'https://plantuml.com/class-diagram

class TodoListApplication{
}

class App1Controller{
}


class TodoList{
    String Title
    Arraylist todoList
    method addItem()
    method removeItem()
    method editItem()
    method saveList()
    method loadList()
    method clearList()
    method setTitle()

}

class TodoItem{
    String Title
    String Description
    String DueDate
    String complete
    method setTitle()
    method setDescription()
    method setDueDate()
    method setComplete()
    method setIncomplete()
}

TodoItem <|- TodoList


@enduml